- name: Update swarm service
  tags: swarm_update
  #TODO Make this a yaml file and commit instead
  docker_swarm_service:
    name: "{{service}}"
    image: "{{image}}"
    publish:
    - published_port: "{{published_port}}"
      target_port: "{{internal_port}}"
    force_update: yes
    mounts:
    - source: /opt/config/datasources.json
      target: /opt/server/server/datasources.json
    replicas: 2
