---
- name: Add the Prometheus user
  user:
    name: prom-sys
    comment: Prometheus System
    uid: 1444

- name: Create prom directories
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
    owner: "1444"
  with_items:
  - /opt/prometheus/config
  - /opt/prometheus/data

- name: Copy prometheus config yml
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/config/prometheus.yml
    owner: 1444

- name: Run prometheus with docker
  docker_container:
    name: prometheus
    image: prom/prometheus:v2.17.1
    user: 1444
    volumes:
      - /opt/prometheus/config:/etc/prometheus/
      - /opt/prometheus/data:/prometheus
    ports:
     - "9090:9090"
    restart: yes
