{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fabric-ca
  labels:
    {{- include "fabric-ca.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      fabric.treetracker.io/component: ca
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values: [hlf-ca, hlf-orderer, hlf-peer-org]
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.clientNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 7054
        - protocol: TCP
          port: 7055
        - protocol: TCP
          port: 7056
        - protocol: TCP
          port: 7057
        - protocol: TCP
          port: 7058
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.monitoringNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 9443
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values: [hlf-ca, hlf-orderer, hlf-peer-org]
{{- end }}
