- name: Unzip directory
  unarchive:
    src: "{{ node_exporter_url }}"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
    - --strip-components=1
    - "{{ node_exporter_folder }}/node_exporter" 

- name: Copy systemd file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start node exporter
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
