apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperledger-explorer
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-explorer
  template:
    metadata:
      labels:
        app: hyperledger-explorer
    spec:
      serviceAccountName: fabric-service-account
      containers:
      - name: explorer
        image: hyperledger/explorer:1.1.8
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: "explorer-db"
        - name: DATABASE_DATABASE
          value: "fabricexplorer"
        - name: DATABASE_USERNAME
          value: "hppoc"
        - name: DATABASE_PASSWD
          value: "password"
        volumeMounts:
        - name: explorer-config
          mountPath: /opt/explorer/app/platform/fabric/config.json
          subPath: config.json
        - name: explorer-connection-profile
          mountPath: /opt/explorer/app/platform/fabric/connection-profile
        - name: crypto-config
          mountPath: /tmp/crypto
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      - name: explorer-db
        image: hyperledger/explorer-db:1.1.8
        ports:
        - containerPort: 5432
        env:
        - name: DATABASE_DATABASE
          value: "fabricexplorer"
        - name: DATABASE_USERNAME
          value: "hppoc"
        - name: DATABASE_PASSWORD
          value: "password"
        volumeMounts:
        - name: explorer-db-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: explorer-config
        configMap:
          name: explorer-config
      - name: explorer-connection-profile
        configMap:
          name: explorer-connection-profile
      - name: crypto-config
        configMap:
          name: crypto-config
      - name: explorer-db-data
        persistentVolumeClaim:
          claimName: explorer-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hyperledger-explorer-service
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-explorer
spec:
  selector:
    app: hyperledger-explorer
  ports:
  - name: explorer
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: explorer-db
  namespace: hyperledger-fabric
  labels:
    app: hyperledger-explorer
spec:
  selector:
    app: hyperledger-explorer
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-db-pvc
  namespace: hyperledger-fabric
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fabric-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer-config
  namespace: hyperledger-fabric
data:
  config.json: |
    {
      "network-configs": {
        "fabric-network": {
          "name": "Hyperledger Fabric Network",
          "profile": "./connection-profile/fabric-network.json"
        }
      },
      "license": "Apache-2.0"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer-connection-profile
  namespace: hyperledger-fabric
data:
  fabric-network.json: |
    {
      "name": "fabric-network",
      "version": "1.0.0",
      "client": {
        "tlsEnable": true,
        "adminCredential": {
          "id": "exploreradmin",
          "password": "exploreradminpw"
        },
        "enableAuthentication": false,
        "organization": "GreenstandMSP",
        "connection": {
          "timeout": {
            "peer": {
              "endorser": "300"
            },
            "orderer": "300"
          }
        }
      },
      "organizations": {
        "GreenstandMSP": {
          "mspid": "GreenstandMSP",
          "adminPrivateKey": {
            "path": "/tmp/crypto/peerOrganizations/greenstand.fabric.local/users/Admin@greenstand.fabric.local/msp/keystore"
          },
          "signedCert": {
            "path": "/tmp/crypto/peerOrganizations/greenstand.fabric.local/users/Admin@greenstand.fabric.local/msp/signcerts"
          }
        }
      },
      "peers": {
        "peer0-greenstand-service.hyperledger-fabric.svc.cluster.local:7051": {
          "tlsCACerts": {
            "path": "/tmp/crypto/peerOrganizations/greenstand.fabric.local/peers/peer0.greenstand.fabric.local/tls/ca.crt"
          },
          "grpcOptions": {
            "ssl-target-name-override": "peer0.greenstand.fabric.local"
          }
        },
        "peer0-cbo-service.hyperledger-fabric.svc.cluster.local:7051": {
          "tlsCACerts": {
            "path": "/tmp/crypto/peerOrganizations/cbo.fabric.local/peers/peer0.cbo.fabric.local/tls/ca.crt"
          },
          "grpcOptions": {
            "ssl-target-name-override": "peer0.cbo.fabric.local"
          }
        },
        "peer0-investor-service.hyperledger-fabric.svc.cluster.local:7051": {
          "tlsCACerts": {
            "path": "/tmp/crypto/peerOrganizations/investor.fabric.local/peers/peer0.investor.fabric.local/tls/ca.crt"
          },
          "grpcOptions": {
            "ssl-target-name-override": "peer0.investor.fabric.local"
          }
        },
        "peer0-verifier-service.hyperledger-fabric.svc.cluster.local:7051": {
          "tlsCACerts": {
            "path": "/tmp/crypto/peerOrganizations/verifier.fabric.local/peers/peer0.verifier.fabric.local/tls/ca.crt"
          },
          "grpcOptions": {
            "ssl-target-name-override": "peer0.verifier.fabric.local"
          }
        }
      },
      "orderers": {
        "orderer-raft-service.hyperledger-fabric.svc.cluster.local:7050": {
          "tlsCACerts": {
            "path": "/tmp/crypto/ordererOrganizations/fabric.local/orderers/orderer.fabric.local/msp/tlscacerts/tlsca.fabric.local-cert.pem"
          },
          "grpcOptions": {
            "ssl-target-name-override": "orderer.fabric.local"
          }
        }
      },
      "channels": {
        "public-channel": {
          "peers": {
            "peer0-greenstand-service.hyperledger-fabric.svc.cluster.local:7051": {},
            "peer0-cbo-service.hyperledger-fabric.svc.cluster.local:7051": {},
            "peer0-investor-service.hyperledger-fabric.svc.cluster.local:7051": {},
            "peer0-verifier-service.hyperledger-fabric.svc.cluster.local:7051": {}
          }
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: hyperledger-fabric
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: hyperledger-fabric
spec:
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: hyperledger-fabric
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fabric-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hyperledger-fabric
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:

    scrape_configs:
      - job_name: 'fabric-peers'
        static_configs:
          - targets: 
            - 'peer0-greenstand-service:9443'
            - 'peer1-greenstand-service:9443'
            - 'peer2-greenstand-service:9443'
            - 'peer0-cbo-service:9443'
            - 'peer1-cbo-service:9443'
            - 'peer0-investor-service:9443'
            - 'peer1-investor-service:9443'
            - 'peer0-verifier-service:9443'
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'fabric-orderers'
        static_configs:
          - targets: ['orderer-raft-service:8443']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'fabric-cas'
        static_configs:
          - targets: 
            - 'fabric-ca-root-service:17054'
            - 'fabric-ca-greenstand-service:17054'
            - 'fabric-ca-cbo-service:17054'
            - 'fabric-ca-investor-service:17054'
            - 'fabric-ca-verifier-service:17054'
        metrics_path: '/metrics'
        scheme: 'http'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: hyperledger-fabric
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data-pvc
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: hyperledger-fabric
spec:
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: hyperledger-fabric
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fabric-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: hyperledger-fabric
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-service:9090
      basicAuth: false
      isDefault: true
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: hyperledger-fabric
data:
  dashboard.yml: |
    apiVersion: 1
    providers:
    - name: 'fabric-dashboards'
      orgId: 1
      folder: 'Fabric'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /etc/grafana/provisioning/dashboards
