default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      - id: terraform_fmt
      # - id: terraform_tflint
        # args:
        #   - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
