---
- name: Add default repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install prometheus kubestack
  community.kubernetes.helm:
    name: prom
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 31.0.0
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('template','files/values.yaml') | from_yaml }}"

- name: Create UI mapping for monitoring
  tags : [mapping]
  community.kubernetes.k8s:
    state: present
    namespace: monitoring
    src: "{{ role_path }}/files/monitor-mapping.yaml"
