---
- name: Add default repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install prometheus operator
  community.kubernetes.helm:
    name: prometheus-community
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 9.4.4
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('file','values.yaml') | from_yaml }}"
