---
- name: Add default repository
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Uninstall old prometheus operator
  community.kubernetes.helm:
    name: prometheus-community
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 9.4.4
    state: absent
    release_namespace: monitoring
    wait: true

# If you get an install error below, run
# kubectl delete crd prometheuses.monitoring.coreos.com prometheusrules.monitoring.coreos.com alertmanagers.monitoring.coreos.com alertmanagerconfigs.monitoring.coreos.com
- name: Install prometheus kubestack
  community.kubernetes.helm:
    name: prom
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 31.0.0
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('template','files/values.yaml') | from_yaml }}"

- name: Create UI mapping for monitoring
  tags : [mapping]
  community.kubernetes.k8s:
    state: present
    namespace: monitoring
    src: "{{ role_path }}/files/monitor-mapping.yaml"
