{{- $seen := dict }}
{{- range $node := .Values.nodes }}
{{- if $node.enabled }}
{{- $n := mergeOverwrite (deepCopy $.Values.defaults) (deepCopy $node) }}
{{- $name := $n.pod.serviceAccountName }}
{{- if not (hasKey $seen $name) }}
{{- $_ := set $seen $name true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "fabric-orderer.labels" $ | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
{{- end }}
