global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: sites
    metrics_path: /metrics
    static_configs:
      - targets: ["dev.treetracker.org:9100", "test.treetracker.org:9100"]
  - job_name: monitor
    metrics_path: /metrics
    static_configs:
      - targets: ["monitoring.treetracker.org:9100"]
