AWSTemplateFormatVersion: '2010-09-09'
Description: Private S3 origin + CloudFront (OAC) with named origin, aliases, and ACM cert (add later)

Parameters:
  BucketName:
    Type: String
    Default: ''
    Description: Optional. Leave blank to let CloudFormation generate a name.

  OriginId:
    Type: String
    Default: S3OriginMain
    Description: Friendly name for the CloudFront Origin (Origin Id).

  PriceClass:
    Type: String
    Default: PriceClass_All
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All
    Description: Lowest cost is PriceClass_100.

Conditions:
  HasBucketName: !Not
    - !Equals
      - !Ref BucketName
      - ''

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - HasBucketName
        - !Ref BucketName
        - !Ref AWS::NoValue
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: OAC for private S3 origin

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub S3 origin for ${AWS::StackName}
        DefaultRootObject: index.html
        PriceClass: !Ref PriceClass

        Origins:
          - Id: !Ref OriginId
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig: {}

        DefaultCacheBehavior:
          TargetOriginId: !Ref OriginId
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${SiteBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

Outputs:
  BucketName:
    Value: !Ref SiteBucket

  OriginId:
    Value: !Ref OriginId

  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName

  DistributionId:
    Value: !Ref CloudFrontDistribution