apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fabric-treetracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://your-git-repo-url/fabric-helm-chart.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hlf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true