apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: root-ca
  namespace: hlf-ca
spec:
  serviceName: root-ca
  replicas: 1
  selector:
    matchLabels:
      app: root-ca
  template:
    metadata:
      labels:
        app: root-ca
    spec:
      containers:
        - name: fabric-ca
          image: {{ .Values.ca.image }}
          ports:
            - containerPort: 7054
          args:
            - sh
            - -c
            - |
              fabric-ca-server start -b {{ .Values.ca.adminUser }}:{{ .Values.ca.adminPassword }} --cfg.affiliations.allowremove --cfg.identities.allowremove