apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer0-greenstand
  namespace: greenstand
spec:
  serviceName: peer0-service
  replicas: 1
  selector:
    matchLabels:
      app: peer0-greenstand
  template:
    metadata:
      labels:
        app: peer0-greenstand
    spec:
      containers:
        - name: peer
          image: {{ .Values.peer.image }}
          ports:
            - containerPort: 7051
            - containerPort: 9443
          env:
            - name: CORE_PEER_ID
              value: {{ .Values.peer.peerID }}
            - name: CORE_PEER_LOCALMSPID
              value: {{ .Values.peer.mspID }}