apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer0-verifier
  namespace: verifier
spec:
  serviceName: peer0-service
  replicas: 1
  selector:
    matchLabels:
      app: peer0-verifier
  template:
    metadata:
      labels:
        app: peer0-verifier
    spec:
      containers:
        - name: peer
          image: {{ .Values.peer.image }}
          ports:
            - containerPort: 7051
            - containerPort: 9443
          env:
            - name: CORE_PEER_ID
              value: peer0.verifier
            - name: CORE_PEER_LOCALMSPID
              value: VerifierMSP