apiVersion: v1
kind: Secret
metadata:
  name: fabric-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.tlsCert }}
  tls.key: {{ .Values.tlsKey }}
  ca.crt: {{ .Values.caCert }}