---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: webmap-be-api
  namespace: webmap
spec:
  cors:
    origins: 
    - '*'
    - https://wallet.treetracker.org
    - https://freetown.treetracker.org
    - https://map.treetracker.org
    - https://forestmatic.com
    - https://app.forestmatic.com
    - https://staging-app.forestmatic.com
