- name: Get secret key for fullchain pem
  shell: "{% raw %} docker secret inspect fullchain.pem --format '{{ .ID }}'{% endraw %}"
  register: fullchain_id

- name: Get secret key for fullchain pem
  shell: "{% raw %} docker secret inspect privkey.pem --format '{{ .ID }}'{% endraw %}"
  register: privkey_id

- name: Get hostname of current node
  shell: "{% raw %} docker node inspect self --format '{{ .Description.Hostname}}' {% endraw %}"
  register: hostname

- name: Remove certbot if running
  docker_swarm_service:
    name: certbot-runner
    state: absent

- name: Update swarm service
  tags: swarm_update
  docker_swarm_service:
    name: reverse-proxy
    image: nginx:1.15.10
    publish:
    - published_port: 80
      target_port: 80
    - published_port: 443
      target_port: 443
    force_update: yes
    secrets:
    - secret_name: fullchain.pem
      secret_id: "{{ fullchain_id.stdout }}"
    - secret_name: privkey.pem
      secret_id: "{{ privkey_id.stdout }}"
    mounts:
    - source: /opt/config/
      target: /etc/nginx/conf.d
    mode: global
