---
- hosts: all
  tasks:
  - name: update and upgrade
    raw: apt-get -y update && apt-get -y upgrade

  - name: install node
    script: scripts/install.nodejs.sh

  - name: install sentry-cli
    script: scripts/install.sentry.cli.sh
