# TODO: Create docker user to associate folders with
- name: make folder for config
  file:
    path: /opt/config
    state: directory
    mode: 0755
# TODO: Need to warn if configs aren't available
- local_action: stat path="{{ role_path }}/files/config.js"
  register: file_details
- name: Copy config
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - config.js
  when: file_details.stat.exists == True

- local_action: stat path="{{ role_path }}/files/datasources.json"
  register: file_details
- name: Copy datasources
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - datasources.json
  when: file_details.stat.exists == True

- local_action: stat path="{{ role_path }}/files/web-map-config.js"
  register: file_details
- name: Copy web map config
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - web-map-config.js
  when: file_details.stat.exists == True

- local_action: stat path="{{ role_path }}/files/prod-nginx.conf"
  register: file_details
- name: Copy datasources
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - prod-nginx.conf
  when: file_details.stat.exists == True
