---
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    setup.template.name: "filebeat-%{[agent.version]}"
    setup.template.pattern: "filebeat-%{[agent.version]}-*"
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
      index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
    setup.ilm.enabled: false
