---
- name: Install elasticsearch, kibana and filebeat
  hosts: localhost-py3
  gather_facts: false
  connection: local
  # ansible_python_interpreter: /usr/bin/python3
  roles:
    - elasticsearch
    - kibana
    - filebeat
