apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  # This creates an all in one deployment, which is not suitable for production
  # See https://www.jaegertracing.io/docs/1.21/operator/#quick-start---deploying-the-allinone-image
spec:
  strategy: allInOne
  allInOne:
    options:
      query:
        base-path: /tracing # Must match mapping file
  ingress:
    enabled: false # Use ambassador instead
