
# From https://www.digitalocean.com/community/tutorials/how-to-set-up-digitalocean-kubernetes-cluster-monitoring-with-helm-and-prometheus-operator
# Define persistent storage for Prometheus (PVC)
prometheusOperator:
  admissionWebhooks:
    enabled: false
  affinity: &nodeAffinity
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: doks.digitalocean.com/node-pool
            operator: In
            values:
            - monitoring-node-pool
            
prometheus:
  prometheusSpec:
    externalUrl: http://prometheus-community-kube-prometheus:9090/prometheus/
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: do-block-storage
          resources:
            requests:
              storage: 40Gi
    affinity: *nodeAffinity

kubeApiServer:
  serviceMonitor:
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: (apiserver_request_duration_seconds_bucket)
      action: drop

# Define persistent storage for Grafana (PVC)
grafana:
  # Set password for Grafana admin user
  adminPassword: {{ adminPassword }}
  persistence:
    enabled: true
    storageClassName: do-block-storage
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
  grafana.ini:
    server:
      root_url: https://{{ domain }}/grafana
    auth.github:
      enabled: true
      allow_sign_up: true
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: Greenstand
      client_id: {{ clientId }}
      client_secret: {{ clientSecret }}
  affinity: *nodeAffinity

# Define persistent storage for Alertmanager (PVC)
alertmanager:
  externalUrl: http://prometheus-community-kube-alertmanager:9093/alertmanager/
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: do-block-storage
          resources:
            requests:
              storage: 5Gi
    affinity: *nodeAffinity

# Change default node-exporter port
prometheus-node-exporter:
  service:
    port: 30206
    targetPort: 30206

# Disable Etcd metrics
kubeEtcd:
  enabled: false

# Disable Controller metrics
kubeControllerManager:
  enabled: false

# Disable Scheduler metrics
kubeScheduler:
  enabled: false
