postgresql:
  enabled: false
  pgPass: {{ ckanDbPassword }}

nodeAffinity: &nodeAffinity
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: doks.digitalocean.com/node-pool
        operator: In
        values:
        - cloud-services-node-pool

ckan:
  sysadminPassword: {{ ckanAdminPassword }}
  siteTitle: "Greenstand CKAN"
  psql:
    initialize: true
    masterUser: {{ ckanDbHost }}
    masterPassword: {{ ckanDbPassword }}
    masterDatabase: ckan
  db:
    ckanDbUrl: {{ ckanDbHost }}
    ckanDbName: ckan
    ckanDbUser: {{ ckanDbUser }}
    ckanDbPassword: {{ ckanDbPassword }}
  datastore:
    RwDbUrl: {{ ckanDbHost }}
    RwDbName: ckan_datastore
    RwDbUser: {{ ckanDbUser }}
    RwDbPassword: {{ ckanDbPassword }}
    RoDbUrl: {{ ckanDbHost }}
    RoDbName: ckan_datastore
    RoDbUser: {{ ckanDbUser }}
    RoDbPassword: {{ ckanDbPassword }}

redis:
  master:
    affinity: 
      nodeAffinity: *nodeAffinity

solr:
  affinity: 
    nodeAffinity: *nodeAffinity
  zookeeper:
    affinity: 
      nodeAffinity: *nodeAffinity

affinity: 
  nodeAffinity: *nodeAffinity

datapusher:
  affinity: 
    nodeAffinity: *nodeAffinity

# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi