{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "fabric-couchdb.labels" $ | nindent 4 }}
spec:
  {{- toYaml $service.spec | nindent 2 }}
{{- end }}
