---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: keycloak-demo-github-endpoint
namespace: ambassador
spec:
  prefix: /auth
  rewrite: ""
  service: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: keycloak
