apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fabric-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-ca-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fabric-storage
  hostPath:
    path: /var/lib/fabric/ca
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-orderer-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fabric-storage
  hostPath:
    path: /var/lib/fabric/orderer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-peer-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fabric-storage
  hostPath:
    path: /var/lib/fabric/peers
