kibanaConfig:
  kibana.yml: |
    server:
      basePath: /extauth/kibana

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1000M"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: doks.digitalocean.com/node-pool
          operator: In
          values:
          - monitoring-node-pool