serviceMonitor:
  enabled: true
  labels:
    release: prometheus-community
es:
  uri: http://elasticsearch-master:9200
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: doks.digitalocean.com/node-pool
          operator: In
          values:
          - monitoring-node-pool