---
# Permit co-located instances for dev/test workflows
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xms512m -Xmx512m"

# Don't require green
clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1000M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: do-block-storage
  resources:
    requests:
      size: 35Gi

nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: doks.digitalocean.com/node-pool
        operator: In
        values:
        - monitoring-node-pool