---
- name: Add sudo users
  user:
    name: '{{ item }}'
    shell: /bin/bash
    groups: sudo,docker
    append: yes
    state: present
  with_items:
    - jon
    - matt
    - zaven
- name: add public key from GitHub
  authorized_key:
    user: jon
    state: present
    key: https://github.com/jonleibowitz.keys

- name: add matt's public key
  authorized_key:
    user: matt
    state: present
    key: https://github.com/mckornfield.keys

- name: add zaven's public key
  authorized_key:
    user: zaven
    state: present
    key: https://github.com/deepwinter.keys

- name: enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: enable basic ufw config
  ufw:
    rule: limit
    name: OpenSSH
    state: enabled

- name: enable tcp ports required for Docker Swarm
  ufw:
    rule: allow
    to_port: '{{ item }}'
    state: reloaded
    proto: tcp
  with_items:
    - 2376
    - 2377
    - 7946

  - name: enable udp ports for Docker Swarm
    ufw:
      rule: allow
      to_port: '{{ item }}'
      state: reloaded
      proto: udp
    with_items:
      - 7946
      - 4789

