apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-database-connection
  namespace: airflow
spec:
  encryptedData:
    database-password: AgCQvBUuSh8RLwuBC+PdijSkRIFQYeBprwphzA5IKoOMH8WtJ84TVwGG36Gd9fLKoPzYTICBDYHinP0ZUSw+mvDUvNEGK5qjCYqjuSLxTdJIwwd/Ff4VImGbWmROQSf7czgPedqoBJ4/ft7hTRvWYNeOgCXYBmj19KmA/2+/SfsGmPuQwkd+ZOLfXc8iZUDBjBvW7WYYengMDSvlARhni73vQIVlL59zMA5Td9tjNMwviFYfAT2hGffQ+/spUk7tzwmTd86UDoKbp3ChuTWhcA/zDDSqbzHVT0QNEsqH8CcrbdYSW58vAWqoTzZU341/LyK5ftbAPt+1HrGYRPkDeESnCgIfq6LEU1RYA+QrUw8szNQXLS52zhrCgByeXZQuk/q8nKiHQ43Bbg5YQkfG/UHMijy+cWV3rmbrjdrxEyS5Woz/tNkJ5KLKvdNWQp8rBPUpfbgQO70Z986M7ShB0Mozj+Wdn4X8V3MdpcucP7rii9dJLDDQR+mzx5lDmsjXDu71Xmzi2aaDChbelrCINKigl7d9BZ2ZucelPdygbllgi4MGyvUo+OOu7Em+S2wDDgG5h0IMnHD0pRDmWA2dLnA79IPPuFrWOL7hLfvLfTWrZLwetDEzSdV6KcLZB/5171CFX7Qu1+gvpSL4X1Gxgja5v7Mje5BBert3WAG8k41mWhU5WWXrcYhP1qZufXgM7RQMnavRFvHbyp3CRUZlxIDQ
  template:
    metadata:
      creationTimestamp: null
      name: airflow-database-connection
      namespace: airflow