# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box/ OS
VAGRANT_BOX = 'bento/ubuntu-18.04'

VM_NAME = 'local-treetracker'

VM_USER = 'root'

HOST_PATH = Dir.getwd

GUEST_PATH = '/home/root/local-treetracker'

#VM_PORT = 8080

Vagrant.configure(2) do |config|

    config.vm.box = VAGRANT_BOX

    config.vm.hostname = VM_NAME

    config.vm.provider "virtualbox" do |v|
        v.name = VM_NAME
        v.memory = 1024
    end

    config.vm.network "private_network", type: "dhcp"

    # config.vm.network "forwarded_port", guest: 80, host: VM_PORT

    config.disksize.size = '25GB'

    config.vm.synced_folder HOST_PATH, GUEST_PATH

    # Prometheus port
    config.vm.network "forwarded_port", guest: 9090, host: 9090

    config.vm.synced_folder '.', '/home' + VM_USER + '', disabled: true

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y git
        apt-get update
        apt-get upgrade -y
        apt-get autoremove -y
    SHELL
end