---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: pgpool-be-api
  namespace: pgpool
spec:
  prefix: /pgpool/
  service: treetracker-pgpool-ambassador-svc
  rewrite: /
  timeout_ms: 0
  cors:
    methods: GET, OPTIONS
    headers:
    - Content-Type
    - Authorization
