---
- name: Add airflow repository
  community.kubernetes.helm_repository:
    name: airflow-stable
    repo_url: https://airflow-helm.github.io/charts

- name: Create secret for database connection
  community.kubernetes.k8s:
    state: present
    namespace: airflow
    src: "{{ role_path }}/files/airflow-database-sealed-secret.yaml"

- name: Install airflow chart
  community.kubernetes.helm:
    name: airflow
    chart_ref: airflow-stable/airflow
    chart_version: 8.4.1
    release_namespace: airflow
    create_namespace: true
    release_values:
      postgresql:
        enabled: false
      externalDatabase:
        type: postgres
        host: db-postgresql-sfo2-nextgen-do-user-1067699-0.db.ondigitalocean.com
        port: 25060
        database: treetracker_dev
        user: doadmin
        passwordSecret: "airflow-database-connection"
        passwordSecretKey: "database-password"

        # use this for any extra connection-string settings, e.g. ?sslmode=disable
        properties: ""
      airflow:
        config:
          AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
          #AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
          #AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
        extraPipPackages:
          - "flask-bcrypt~=0.7.1"
      web:
        baseUrl: "http://dev-k8s.treetracker.org/airflow"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      scheduler:
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      workers:
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      flower:
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
    #ingress:
    # enabled: true
    #web:
    #baseUrl: "http://dev.airflow.treetracker.org/"
    #flower:
    #urlPrefix: "/flower"
    #NOTE: ingress is created, but need to use external-dns chart to make LB/DNS


- name: Create UI mapping for control panel
  community.kubernetes.k8s:
    state: present
    namespace: airflow
    src: "{{ role_path }}/files/panel-mapping.yaml"

