---
- name: Add airflow repository
  community.kubernetes.helm_repository:
    name: airflow-stable
    repo_url: https://airflow-helm.github.io/charts

- name: Install airflow chart
  community.kubernetes.helm:
    name: airflow
    chart_ref: airflow-stable/airflow
    chart_version: 7.16.0
    release_namespace: airflow
    create_namespace: true
    release_values:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: doks.digitalocean.com/node-pool
                  operator: In
                  values:
                    - cloud-services-node-pool

   
