# Minimal role for installing Docker CE on Ubuntu
# Stolen from https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933#gistcomment-2761682
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce','python3-docker','python3-pip']
    state: present
    update_cache: yes

- name: enable tcp ports required for Docker Swarm
  ufw:
    rule: allow
    to_port: '{{ item }}'
    state: reloaded
    proto: tcp
  with_items:
    - 2376
    - 2377
    - 7946

- name: enable udp ports for Docker Swarm
  ufw:
    rule: allow
    to_port: '{{ item }}'
    state: reloaded
    proto: udp
  with_items:
    - 7946
    - 4789
    
- name: Install docker python
  pip:
    name:
    - docker>=3.7.2
    - request>=2.20.1
# TODO: Create docker user to associate folders with
- name: make folder for config
  file:
    path: /opt/config
    state: directory
    mode: 0755
# TODO: Need to warn if configs aren't available
- local_action: stat path="{{ role_path }}/files/config.js"
  register: file_details
- name: Copy config
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - config.js
  when: file_details.stat.exists == True

- local_action: stat path="{{ role_path }}/files/datasources.json"
  register: file_details
- name: Copy datasources
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - datasources.json
  when: file_details.stat.exists == True

- local_action: stat path="{{ role_path }}/files/web-map-config.js"
  register: file_details
- name: Copy web map config
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - web-map-config.js
  when: file_details.stat.exists == True

- local_action: stat path="{{ role_path }}/files/prod-nginx.conf"
  register: file_details
- name: Copy datasources
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - prod-nginx.conf
  when: file_details.stat.exists == True
