# Minimal role for installing Docker CE on Ubuntu
# Stolen from https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933#gistcomment-2761682
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce','python3-docker','python3-pip', 'build-essential', 'libssl-dev','libffi-dev']
    state: present
    update_cache: yes

- name: enable tcp ports required for Docker Swarm
  ufw:
    rule: allow
    to_port: '{{ item }}'
    state: reloaded
    proto: tcp
  with_items:
    - 2376
    - 2377
    - 7946

- name: enable udp ports for Docker Swarm
  ufw:
    rule: allow
    to_port: '{{ item }}'
    state: reloaded
    proto: udp
  with_items:
    - 7946
    - 4789
    
- name: Install docker python
  pip:
    name:
    - pip>=9.0.1
    - docker>=3.7.2
    - passlib>=1.6
    extra_args: --upgrade
