# Minimal role for installing Docker CE on Ubuntu
# Stolen from https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933#gistcomment-2761682
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce','python3-docker','python3-pip']
    state: present
    update_cache: yes
- name: Install docker python
  pip:
    name:
    - docker>=3.7.2
    - request>=2.20.1
# TODO: Create docker user to associate folders with
- name: make folder for config
  file:
    path: /opt/config
    state: directory
    mode: 0755
# TODO: Need to warn if configs aren't available
- name: Copy config
  copy:
    src: "{{item}}"
    dest: "/opt/config/{{item}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  with_items:
  - config.js
  - datasources.json
