apiVersion: v1
kind: Service
metadata:
  name: app-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmqcluster-sample-server
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
