---
- name: Add elastic repository
  tags: [elasticsearch]
  community.kubernetes.helm_repository:
    name: elastic
    repo_url: https://helm.elastic.co

- name: Install elasticsearch
  tags: [elasticsearch]
  community.kubernetes.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    chart_version: 7.12.0
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('file','values.yaml') | from_yaml }}"

- name: Add prom repository
  tags: [elasticsearch, exporter]
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install elasticsearch exporter
  tags: [elasticsearch, exporter]
  community.kubernetes.helm:
    name: elasticsearch-exporter
    chart_ref: prometheus-community/prometheus-elasticsearch-exporter
    chart_version: 4.6.1
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('file','exporter-values.yaml') | from_yaml }}"
