---
- file:
    state: directory
    name: src

- name: clone {{ repo }}
  tags: build
  git:
    repo: "{{repo}}"
    depth: 1
    version: "{{ version }}"
    dest: "{{ build_dir }}"
  register: gitresult

- name: copy dockerfile
  tags: build
  copy:
    src: "{{ dockerfile }}"
    dest: "{{ build_dir }}/Dockerfile"

- name: copy nginx conf
  tags: build
  copy:
    src: "{{ nginx_conf }}"
    dest: "{{ build_dir }}/{{ nginx_conf }}"

- name: create tag
  tags: build
  set_fact:
    tag: "{{ version }}-{{ gitresult.after }}"

- name: login to registry
  docker_login:
    registry: "{{registry_url}}"
    username: "{{registry_username}}"
    password: "{{registry_password}}"

- name: Build {{image_name}} image and push
  tags: build
  docker_image:
    name: "{{registry_url}}/{{image_name}}"
    build:
      path: "{{ build_dir }}"
      pull: no
    tag: "{{item}}"
    state: present
    push: yes
    force_tag: yes
    force_source: yes
    source: build
  with_items:
  - latest
  - "{{tag}}"
