---
- shell: 'date +"%s"'
  register: timestamp

- file:
    state: directory
    name: src

- name: clone {{ repo }}
  tags: build
  git:
    repo: "{{repo}}"
    depth: 1
    version: "{{ version }}"
    dest: "{{ build_dir }}"

- shell: "cd {{ build_dir }}; git rev-parse --short HEAD"
  tags: build
  register: sha

- name: copy Dockerfile
  tags: build
  copy:
    src: "{{ dockerfile }}"
    dest: "{{ build_dir }}/Dockerfile"

- name: copy Nginx conf
  tags: build
  copy:
    src: nginx.conf
    dest: "{{ build_dir}}/nginx.conf"

- name: generate tag
  tags: build
  set_fact:
    tag: "{{ version }}-{{ timestamp.stdout }}-{{ sha.stdout }}"

- name: Run npm install in client folder
  tags: build
  npm:
    path: "{{build_dir}}/client"

- name: Build {{image_name}} image and push
  tags: build
  docker_image:
    path: "{{ build_dir }}"
    name: "{{registry_url}}/{{image_name}}"
    tag: "{{item}}"
    state: present
    push: yes
    force: yes
  with_items:
  - latest
  - "{{tag}}"
