---
- name: ensure src dir created
  file:
    state: directory
    name: src

- name: clone admin-api
  tags: build
  git:
    repo: "{{repo}}"
    depth: 1
    version: "{{ version }}"
    dest: "{{ build_dir }}"
    update: yes
  register: gitresult

- name: copy dockerfile
  tags: build
  copy:
    src: "{{ dockerfile }}"
    dest: "{{ build_dir }}/Dockerfile"

- name: create tag
  tags: build
  set_fact:
    tag: "{{ version }}-{{ gitresult.after }}"

- name: copy Nginx conf
  tags: build
  copy:
    src: nginx.conf
    dest: "{{ build_dir}}/nginx.conf"

- name: Run npm install in client folder
  tags: build
  npm:
    path: "{{build_dir}}/client"

- name: Run npm build in client folder
  shell: "cd {{ build_dir }}/client; npm run build"
  tags: build

- name: Build {{image_name}} image and push
  tags: build
  docker_image:
    path: "{{ build_dir }}"
    name: "{{registry_url}}/{{image_name}}"
    tag: "{{item}}"
    state: present
    push: yes
    force: yes
  with_items:
  - latest
  - "{{tag}}"
