---

- name: Add lebenitza repository
  tags: [curator]
  community.kubernetes.helm_repository:
    name: lebenitza
    repo_url: https://lebenitza.github.io/charts

- name: Install curator
  tags: [curator]
  community.kubernetes.helm:
    name: elasticsearch-curator
    chart_ref: lebenitza/elasticsearch-curator
    chart_version: 3.0.2
    release_namespace: monitoring
    create_namespace: true
    values: "{{ lookup('file','values.yaml') | from_yaml }}"
