{{- range $name, $data := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "fabric-peers.labels" $ | nindent 4 }}
data:
  {{- toYaml $data | nindent 2 }}
{{- end }}
