# Minimal role for installing Docker CE on Ubuntu
# Stolen from https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933#gistcomment-2761682

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    force_apt_get: True
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - python3-docker
      - python3-pip
      - python-setuptools
      - build-essential
      - libssl-dev
      - libffi-dev
    state: present
    update_cache: yes

- name: Install docker python
  pip:
    executable: pip3
    name:
      - docker>=4.2.0
    extra_args: --upgrade
