- name: Ensure proxy network exists
  docker_network:
    name: proxy
    driver: overlay

- name: Update swarm service
  tags: swarm_update
  docker_swarm_service:
    name: "{{service}}"
    image: "{{image}}"
    publish:
    - published_port: "{{published_port}}"
      target_port: "{{internal_port}}"
    force_update: yes
    mounts:
    - source: /opt/config/web-map-config.js
      target: /var/www/js/config.js
    replicas: 2
    networks:
    - proxy
