apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderer-raft
  namespace: hyperledger-fabric
  labels:
    app: orderer-raft
    component: orderer
spec:
  serviceName: orderer-raft-headless
  replicas: 5
  selector:
    matchLabels:
      app: orderer-raft
  template:
    metadata:
      labels:
        app: orderer-raft
        component: orderer
    spec:
      serviceAccountName: fabric-service-account
      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:2.5.4
        ports:
        - containerPort: 7050
          name: orderer-port
        - containerPort: 8443
          name: operations
        - containerPort: 9443
          name: metrics
        env:
        - name: FABRIC_LOGGING_SPEC
          value: "INFO"
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: "0.0.0.0"
        - name: ORDERER_GENERAL_LISTENPORT
          value: "7050"
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: "BFT"
        - name: ORDERER_GENERAL_GENESISFILE
          value: "/var/hyperledger/orderer/genesis.block"
        - name: ORDERER_GENERAL_LOCALMSPID
          value: "OrdererMSP"
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: "/var/hyperledger/orderer/msp"
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: "/var/hyperledger/orderer/tls/server.key"
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: "/var/hyperledger/orderer/tls/server.crt"
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "[/var/hyperledger/orderer/tls/ca.crt]"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: "/var/hyperledger/orderer/tls/server.crt"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: "/var/hyperledger/orderer/tls/server.key"
        - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
          value: "[/var/hyperledger/orderer/tls/ca.crt]"
        - name: ORDERER_OPERATIONS_LISTENADDRESS
          value: "0.0.0.0:8443"
        - name: ORDERER_METRICS_PROVIDER
          value: "prometheus"
        - name: ORDERER_METRICS_STATSD_ADDRESS
          value: "0.0.0.0:9443"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ORDERER_GENERAL_CLUSTER_LISTENADDRESS
          value: "0.0.0.0"
        - name: ORDERER_GENERAL_CLUSTER_LISTENPORT
          value: "7050"
        - name: ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE
          value: "/var/hyperledger/orderer/tls/server.crt"
        - name: ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY
          value: "/var/hyperledger/orderer/tls/server.key"
        - name: ORDERER_CONSENSUS_TYPE
          value: "etcdraft"
        - name: ORDERER_CONSENSUS_ETCDRAFT_CONSENTERS
          value: |
            - host: orderer-raft-0.orderer-raft-headless.hyperledger-fabric.svc.cluster.local
              port: 7050
              client_tls_cert: /var/hyperledger/orderer/tls/server.crt
              server_tls_cert: /var/hyperledger/orderer/tls/server.crt
            - host: orderer-raft-1.orderer-raft-headless.hyperledger-fabric.svc.cluster.local
              port: 7050
              client_tls_cert: /var/hyperledger/orderer/tls/server.crt
              server_tls_cert: /var/hyperledger/orderer/tls/server.crt
            - host: orderer-raft-2.orderer-raft-headless.hyperledger-fabric.svc.cluster.local
              port: 7050
              client_tls_cert: /var/hyperledger/orderer/tls/server.crt
              server_tls_cert: /var/hyperledger/orderer/tls/server.crt
            - host: orderer-raft-3.orderer-raft-headless.hyperledger-fabric.svc.cluster.local
              port: 7050
              client_tls_cert: /var/hyperledger/orderer/tls/server.crt
              server_tls_cert: /var/hyperledger/orderer/tls/server.crt
            - host: orderer-raft-4.orderer-raft-headless.hyperledger-fabric.svc.cluster.local
              port: 7050
              client_tls_cert: /var/hyperledger/orderer/tls/server.crt
              server_tls_cert: /var/hyperledger/orderer/tls/server.crt
        command: ["sh"]
        args:
        - -c
        - |
          echo "Starting orderer node: $POD_NAME"
          # Generate orderer configuration
          mkdir -p /var/hyperledger/orderer/msp/admincerts
          mkdir -p /var/hyperledger/orderer/msp/cacerts
          mkdir -p /var/hyperledger/orderer/msp/keystore
          mkdir -p /var/hyperledger/orderer/msp/signcerts
          mkdir -p /var/hyperledger/orderer/tls
          
          # Start the orderer
          orderer
        volumeMounts:
        - name: orderer-data
          mountPath: /var/hyperledger/production/orderer
        - name: orderer-msp
          mountPath: /var/hyperledger/orderer/msp
        - name: orderer-tls
          mountPath: /var/hyperledger/orderer/tls
        - name: genesis-block
          mountPath: /var/hyperledger/orderer/genesis.block
          subPath: genesis.block
        - name: orderer-config
          mountPath: /etc/hyperledger/fabric
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: orderer-msp
        configMap:
          name: orderer-msp-config
      - name: orderer-tls
        configMap:
          name: orderer-tls-config
      - name: genesis-block
        configMap:
          name: genesis-block-config
      - name: orderer-config
        configMap:
          name: orderer-config
  volumeClaimTemplates:
  - metadata:
      name: orderer-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fabric-storage
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: orderer-raft-headless
  namespace: hyperledger-fabric
  labels:
    app: orderer-raft
spec:
  clusterIP: None
  selector:
    app: orderer-raft
  ports:
  - name: orderer-port
    port: 7050
    targetPort: 7050
  - name: operations
    port: 8443
    targetPort: 8443
  - name: metrics
    port: 9443
    targetPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: orderer-raft-service
  namespace: hyperledger-fabric
  labels:
    app: orderer-raft
spec:
  selector:
    app: orderer-raft
  ports:
  - name: orderer-port
    port: 7050
    targetPort: 7050
  - name: operations
    port: 8443
    targetPort: 8443
  - name: metrics
    port: 9443
    targetPort: 9443
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-config
  namespace: hyperledger-fabric
data:
  orderer.yaml: |
    General:
      ListenAddress: 0.0.0.0
      ListenPort: 7050
      TLS:
        Enabled: true
        PrivateKey: /var/hyperledger/orderer/tls/server.key
        Certificate: /var/hyperledger/orderer/tls/server.crt
        RootCAs:
          - /var/hyperledger/orderer/tls/ca.crt
      Cluster:
        SendBufferSize: 10
        ClientCertificate: /var/hyperledger/orderer/tls/server.crt
        ClientPrivateKey: /var/hyperledger/orderer/tls/server.key
        ListenPort: 7050
        ListenAddress: 0.0.0.0
        ServerCertificate: /var/hyperledger/orderer/tls/server.crt
        ServerPrivateKey: /var/hyperledger/orderer/tls/server.key
      GenesisMethod: BFT
      GenesisFile: /var/hyperledger/orderer/genesis.block
      LocalMSPDir: /var/hyperledger/orderer/msp
      LocalMSPID: OrdererMSP
      Profile:
        Enabled: false
        Address: 0.0.0.0:6060
      BCCSP:
        Default: SW
        SW:
          Hash: SHA2
          Security: 256
          FileKeyStore:
            KeyStore:
      Authentication:
        TimeWindow: 15m
    FileLedger:
      Location: /var/hyperledger/production/orderer
      Prefix: hyperledger-fabric-ordererledger
    Consensus:
      WALDir: /var/hyperledger/production/orderer/etcdraft/wal
      SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
    Operations:
      ListenAddress: 0.0.0.0:8443
      TLS:
        Enabled: false
    Metrics:
      Provider: prometheus
      Statsd:
        Network: udp
        Address: 0.0.0.0:9443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-msp-config
  namespace: hyperledger-fabric
data:
  # Placeholder - these should be replaced with actual certificates
  admincerts.pem: |
    -----BEGIN CERTIFICATE-----
    # Orderer Admin Certificate
    -----END CERTIFICATE-----
  cacerts.pem: |
    -----BEGIN CERTIFICATE-----
    # CA Certificate
    -----END CERTIFICATE-----
  signcerts.pem: |
    -----BEGIN CERTIFICATE-----
    # Orderer Signing Certificate  
    -----END CERTIFICATE-----
  keystore.key: |
    -----BEGIN PRIVATE KEY-----
    # Orderer Private Key
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-tls-config
  namespace: hyperledger-fabric
data:
  # Placeholder - these should be replaced with actual TLS certificates
  server.crt: |
    -----BEGIN CERTIFICATE-----
    # TLS Server Certificate
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    # TLS Server Private Key
    -----END PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    # TLS CA Certificate
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-block-config
  namespace: hyperledger-fabric
data:
  # Placeholder - this should be replaced with actual genesis block
  genesis.block: |
    # Genesis Block Binary Data (Base64 encoded)
