---
- name: deploy update to sqs consumer
  hosts: all
  become: yes
  serial: 1
  tasks:
    
    - name: stop sqs consumer
      systemd:
        name: treetracker-pipeline-consumer
        state: stopped

    - name: remove microservice api directory
      file:
        state: absent
        path: ~/treetracker-pipeline-consumer

    - name: ensure directory exists
      file:
        path: ~/treetracker-pipeline-consumer
        state: directory

    - name: copy sqs consumer
      unarchive:
        src: ../../build/treetracker-pipeline-consumer.tar.gz
        dest: ~/treetracker-pipeline-consumer

    - name: restart sqs consumer
      systemd:
        name: treetracker-pipeline-consumer
        enabled: true
        state: restarted
